[package]
name = "printer-sim"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
mdns-sd = "0.21"
ipp = { version = "7", default-features = false }
bytes = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0.20"
num-traits = "0.2.19"
